### PR TITLE
BugFix: removed russian letter "л" from mapping to "n"

### PR DESCRIPTION
**Pull request by dmitry-kotorov**

### CODE REVIEW

**Comment by isoos** [comment]
I have not much insight on how other Cyrillic letter are treated in the transformations. Is this something that is clearly wrong compared to the others?

**Comment by dmitry-kotorov** [comment]
This one is clearly wrong. I've faced an issue in production related to this one. I did not test others, but now I think it is good idea to test the rest of russian alphabet)

**Comment by isoos** [comment]
Ah, sorry for leaving this pending so much.

The PR reminded me of an article about lookalikes (like `K` (`\u004B`) and `K` (Kelvin sign `\u212A`). Some of the Cyrillic letter are probably in a similar category. It is possible that we should evolve the API of this package a bit, and provide options to reduce lookalikes to their base components, as `л` mapping to `n` is basically is just that. wdyt?

**Comment by AlexanderFarkas** [comment]
I'm not sure why it's mapped at all. "л" is a Cyrillic letter without any diacritic signs, while "n" is a latin letter. I believe the library shouldn't do any romanisation of characters.
It just looks like a bug to me.

**Comment by isoos** [comment]
I've updated the code with a comment and also bumped the version. Published as `0.1.5`. It is not clear to me yet, to what extent I want to drill into this issue, any comment and suggestion is welcome. Closing this issue though, as the code has been updated.

**Pull request closed without merging**
